### ISSUE TITLE
handleOpenURL() does not seem to be triggered when cliking a link when the App is closed

### ISSUE THREAD

**Issue by orenagiv** [EddyVerbruggen/Custom-URL-scheme#2]
Hi there,

The plugin seems to be working fantastic!
Once question though - The handleOpenURL(url) function does not seem to be triggered when clicking a link when the App is closed. It seems to work perfectly if the App is working in the background.

(Tested with PhoneGAP Build 3.1)

Thanks!
Oren.

**Comment by msalman** [comment]
I am having cordova version 4.1.2 and still facing this issue ... on which version it worked for you orenagiv ?

**Comment by EddyVerbruggen** [comment]
@msalman That's not the Cordova-iOS version but the CLI version. Which Cordova-iOS version are you on? Problems arise with 3.7.0 and up.

**Comment by msalman** [comment]
I use cordova -v to check the cordova version. In cordova lib project version file contains 3.7.0.

Sorry for being dumb, let me know if I can check the version via some command.

**Comment by msalman** [comment]
finally..

cordova platform version ios
Installed platforms: android 3.6.4, ios 3.7.0

**Comment by EddyVerbruggen** [comment]
Yeah, 3.7.0 has the bug. Hopefully https://issues.apache.org/jira/browse/CB-7606 will be resolved in time for 3.8.0.

**Comment by EddyVerbruggen** [comment]
[Shazron has fixed the bug for 3.8.0](https://issues.apache.org/jira/browse/CB-7606) - I just tested it and it works fine :)

**Comment by kaansoral** [comment]
Off topic, I recently inspected the cordova cli/platform versioning and how the cli handles platform libraries (mainly to write a tool to know when a new platform version is available and live)
How did you manage to test 3.8.0 manually, as the CLI seems to fetch 3.7.0 as hard coded in 4.2.0?
(I guess you can trick the CLI by editing that hard coded version, but I'm just wondering whether there is an easy/obvious way)

**Comment by EddyVerbruggen** [comment]
Hi. Yeah, Shazron explained how to do this in the apache issue mentioned above. See his test-steps.

**Comment by kaansoral** [comment]
Thanks a lot for the pointer, it's very very helpful, After spending years hunting various mobile/cordova/webkit issues like these, it makes sense to just track https://git-wip-us.apache.org/repos/asf and add plugins/platforms manually when there are fixes that would take a long time to reach production, I'm even thinking of implementing a custom routine to parse for such changes and report them automatically / suggest utilising manual versions / upgrades

**Comment by laurilehmijoki** [comment]
I manually applied the [fix](https://github.com/apache/cordova-ios/commit/ed54ddf2cc6e2b746a406e15e99f549846cd171b) into my Cordova iOS 3.7.0 project, because I was unable to upgrade to 3.8.0 via `cordova plugin update ios`.

Note to my future self: once the Cordova iOS 3.8.0 is available via the command `cordova plugin update ios`, revert the manual application of the fix and then run `cordova plugin update ios`.

**Comment by EddyVerbruggen** [comment]
Cordova-ios 3.8.0 has just been released, including [the fix for CB-7606](https://issues.apache.org/jira/browse/CB-7606). This should fix your trouble, thanks for the patience.

**Comment by mirko77** [comment]
I am using 3.8 now and `handleOpenURL()` is called upon cold start but NOT when the app is just resumed (as already opened). I am testing on iOS 7 & 8, is this the expected behaviour?

**Comment by symbiat** [comment]
Anyone looked at this approach ?
https://medium.com/angularjs-articles/deep-linking-in-ionic-mobile-applications-44d8b4685bb3

**Comment by EddyVerbruggen** [comment]
@symbiat I like it

**Comment by qkdreyer** [comment]
I'm using the new PhoneGap Build version cli-5.1.1 and still experiencing this issue.

handleOpenURL fires nicely when app is in the background, but not lauching from cold start.

**Comment by alexszilagyi** [comment]
@qkdreyer : Facing the same thing, have you managed to solve this? Thanks!

**Comment by qkdreyer** [comment]
Not yet sadly :/

**Comment by amardeepthadisetty** [comment]
Hi, I have used custom url plugin in my app and build it using phonegap build.
Here is my code:
<script type="text/javascript" src="phonegap.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        //alert("hello");
        var delay = 3000; //Your delay in milliseconds

        setTimeout(function(){
         window.location = "home.html";
       }, delay);
        document.addEventListener("deviceready", onDeviceReady, false);

        function onDeviceReady() {
        // Now safe to use the Cordova API
        alert("device is ready");

        function handleOpenURL(url) {
          setTimeout(function() {
            alert("received url: " + url);
          }, 0);
        }
    }

    });//end of document ready
    </script>

//end of code
I have opened a url in my mobile browser(http://fornextit.com/south/test.html) and clicked on the link of my app. My app is opening however the url is not firing. Please help........

**Comment by easym0de** [comment]
Cold Start Still not working for me. 

Using cordova CLI 5.1.1 and Cordova iOS version 3.8.0.

Works fine in android and in iOS app running in background mode.

When tried with cold start, app runs but handleOpenURL never fired.

**Comment by easym0de** [comment]
OK I fixed the issue for "Cordova CLI 5.1.1 - Cordova iOS version 3.8.0" by doing the following:

Inside CDVHandleOpenURL.m:

Changed 

NSString* jsString = [NSString stringWithFormat:@"document.addEventListener('deviceready',function(){if (typeof handleOpenURL === 'function') { handleOpenURL(\"%@\");}});", url];

to

NSString* jsString = [NSString stringWithFormat:@"if (typeof handleOpenURL === 'function') { handleOpenURL(\"%@\");} else { window._savedOpenURL = \"%@\"; }", url, url];

Then in Javascript code, introduced the following:

setTimeout(function() {
                    if(typeof window._savedOpenURL != 'undefined'){
                        window.handleOpenURL(window._savedOpenURL);
                    }
                }, 0);

Hope this helps.

**Comment by souly1** [comment]
@symbiat, great reference, thanks!

**Comment by yagao0o** [comment]
@easym0de 
Thanks,It work for me.

**Comment by pushpendra996** [comment]
Hi, There
I am trying to open a another tab on link click but it direct goes to the home screen means goes to the (Login) which i have set into run() method.
i had try to catch the URL by witch i am trying to come on the app. but i think so my   

function handleOpenURL(url) {
    setTimeout(function () {
        var event = new CustomEvent('LaunchUrl', {detail: {'url': url}});
        alert (event);
        window.dispatchEvent(event);
    }, 0);
}

function is not working. is any one here what should i do.................

**Comment by laxmikantp382** [comment]
Hello Guy's,

You can easily sort out this problem.

In "CDVHandleOpenURL.m" file you need to change code as below

NSString* jsString = [NSString stringWithFormat:@"document.addEventListener('deviceready',function(){if (typeof handleOpenURL === 'function') { handleOpenURL(\"%@\");}});", url];

To

NSString* jsString = [NSString stringWithFormat:@"if (typeof handleOpenURL === 'function') { handleOpenURL(\"%@\");} else { window._savedOpenURL = \"%@\"; }", url, url];


this will work perfectly.


Best of luck

**Comment by celron** [comment]
Great work from @easym0de, this solution to update the cordova platform code solved the problem for me.  What ways is there to package it into something that can be added to the git://git.apache.org/cordova-ios.git to make a more permanent solution?

**Comment by rondoe** [comment]
In my case the problem was solved after adding gap://ready to my Content-Security-Policy. I was wondering why safari gave me so many errors with gap://ready. so i added it, and it was solved. now handleOpenURL works as expected.

**Comment by abdurraqeeb** [comment]
How can i make a script that if anyone visits my website then his default home page is my websites URL

**Comment by emirhosseini** [comment]
None of these solutions work for me. Still having this issue in 2018. Navigating to a hosted login page, logging in which then redirects back to the app. Works fine in iOs emulator and android. Just not on actual ios device...
